In [1]:
import pandas as pd
import os

In [2]:
scores=pd.read_csv("/Users/rm026/Partners HealthCare Dropbox/Ross Macfadyen/Schmahmann_SCA_Atrophy/schmahmann_connectivity_filelist.csv")
scores=scores[['mrn']+[col for col in scores.columns if col.startswith('Sec')]]

df=pd.read_csv("/Users/rm026/Documents/schmahmann/ground_truth_cnrs_schmahmann_wip.csv")
new_names={df.columns[2*i+1]:df.columns[2*i+1]+': '+colname[5:] for i, colname in enumerate(scores.columns[1:])}
scores.columns=['MRN'] + list(new_names.values())
new_names.update({f'explanation: {old}':f'explanation: {new}' for old, new in new_names.items()})
df.rename(columns=new_names, inplace=True)
df

,MRN,attention a1: DifficultFocus,explanation: attention a1: DifficultFocus,attention a2: EasilyDistracted,explanation: attention a2: EasilyDistracted,attention a3: OntheGo,explanation: attention a3: OntheGo,attention a4: FeelsCompelled,explanation: attention a4: FeelsCompelled,attention a5: FeelsDriven,...,social a31: Argumentative,explanation: social a31: Argumentative,social b32: immature,explanation: social b32: immature,social b33: Unaware,explanation: social b33: Unaware,social b34: Manner,explanation: social b34: Manner,social b35: Trusting,explanation: social b35: Trusting
0,6596307,0.0,"1: The report states ""Memory, comprehension an...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,1.0,"1: ""Fully alert and engaged throughout the his...",0.0,NaN,0.0,NaN
1,6890459,0.0,"1: The report states ""Memory, thinking and con...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,1.0,"1: The note states ""the story presented in a c...",0.0,NaN,0.0,NaN
2,6868827,0.0,1: There is no mention of difficulty maintaini...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
3,7298779,0.0,"1: The text states ""no significant cognitive d...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,1.0,"1: Text states, ""the story presented in a clea...",0.0,NaN,0.0,NaN
4,8231339,0.0,"1: The text describes the patient as ""Fully al...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,3699762,0.0,"1: The exam states ""Orientation: is normal,"" ""...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,1.0,"1: ""Behavior normal""; no mention of passive, i...",0.0,NaN,0.0,NaN,0.0,NaN
81,3815202,2.0,"2: The text states ""Ritalin which is helpful w...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
82,1175258,1.0,1: There is no mention of difficulty maintaini...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
83,1847722,1.0,"1: The report explicitly states ""No change in ...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN
84,8671698,0.0,"1: The text states: ""He was oriented with good...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,1.0,1: Patient presents history in clear and logic...,1.0,1: No indication of inappropriate social behav...,0.0,NaN

In [3]:
merge=pd.merge(df, scores, on='MRN',suffixes=['_me','_sch'], how='left')

In [48]:

import numpy as np

check_col=[]
for i, row in merge.iterrows():
    check=[]

    for col in scores.columns[1:]:

        if int(row[col+'_me'])==2:# if I already checked, skip
            continue 

        if np.isnan(row[col+'_sch']) or row[col+'_sch']!=0: # if I say no/unknown and schmahmann finds something
            check.append(col)


    check_col.append(check)

merge['needs_checking']=check_col
merge

,MRN,attention a1: DifficultFocus_me,explanation: attention a1: DifficultFocus,attention a2: EasilyDistracted_me,explanation: attention a2: EasilyDistracted,attention a3: OntheGo_me,explanation: attention a3: OntheGo,attention a4: FeelsCompelled_me,explanation: attention a4: FeelsCompelled,attention a5: FeelsDriven_me,...,psychosis b27: Indifferent_sch,social a28: Angry_sch,social a29: Upset_sch,social a30: Intolerant_sch,social a31: Argumentative_sch,social b32: immature_sch,social b33: Unaware_sch,social b34: Manner_sch,social b35: Trusting_sch,needs_checking
0,6596307,0.0,"1: The report states ""Memory, comprehension an...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[attention a1: DifficultFocus, attention a2: E..."
1,6890459,0.0,"1: The report states ""Memory, thinking and con...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,"[attention a1: DifficultFocus, attention a2: E..."
2,6868827,0.0,1: There is no mention of difficulty maintaini...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[attention a1: DifficultFocus, attention a2: E..."
3,7298779,0.0,"1: The text states ""no significant cognitive d...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,"[attention a2: EasilyDistracted, attention a3:..."
4,8231339,0.0,"1: The text describes the patient as ""Fully al...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[attention a1: DifficultFocus, attention a2: E..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,3699762,0.0,"1: The exam states ""Orientation: is normal,"" ""...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[attention a1: DifficultFocus, attention a2: E..."
81,3815202,2.0,"2: The text states ""Ritalin which is helpful w...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[attention a2: EasilyDistracted, attention a3:..."
82,1175258,1.0,1: There is no mention of difficulty maintaini...,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[attention b8: MentallyStuck]
83,1847722,1.0,"1: The report explicitly states ""No change in ...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[attention a1: DifficultFocus, attention a2: E..."
84,8671698,0.0,"1: The text states: ""He was oriented with good...",0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[attention a1: DifficultFocus, attention a2: E..."

In [49]:

import json
root_folder="/Users/rm026/Documents/schmahmann/schmahmann_cnrs_and_similarities_redo/_separated/"

# keywords=['phonem','fluen','categor','vegetabl','verbal con','verbal','registr','digit ','digits','digit,','digit.','drawn','draw','cube','similarit','go-no','no-go','affect','labile','apath','irritab']
# keywords={'attention a':['attention', 'focus','distract', 'restless', 'compel', 'compuls', 'habit', 'repetitive', 'inflexib', 'worry'], 
#           'attention b':['anxi', 'inappropri', ], 
#           'emotion a':['interrupt', 'emotion', 'worry','laugh',  'fear', 'panic'], 
#           'emotion b':['pleasure', 'enjoy', 'pessim', 'hopeless','dissatis', 'depress', 'sad',], 
#           'autism a':[ 'sensory', 'repetit', 'habit'], 
#           'autism b':['sensory','sensitiv', 'overwhelm', 'overstimul'],
#           'psychosis a':['illogical', 'inappropri','rambling', 'schizo', 'irrational', 'paranoi', 'hallucinat'],
#           'psychosis b':['interaction', 'aloof', 'affect', 'reactivity', 'indifferen'],
#           'social a':['anger', 'angry', 'aggress', 'irrita', 'argument','defiant','intoler', 'protective'], 
#           'social b':['appropri', 'trustful', 'trusting', 'trick', 'manipulat']
#           }
# keywords=keywords.split()
keywords=json.load(open('cnrs_keywords.json'))
keywords={new_names[section]:words.split(', ') for words, section in keywords.items()}
keywords

{'attention a1: DifficultFocus': ['focus', 'attention', 'careless', 'detail'],
 'attention a2: EasilyDistracted': ['distract', 'stimuli'],
 'attention a3: OntheGo': ['on the go', 'restless'],
 'attention a4: FeelsCompelled': ['compelled', 'compulsion', 'repetitive'],
 'attention a5: FeelsDriven': ['driven'],
 'attention b6: Worries': ['worry', 'worries'],
 'attention b7: Repeats': ['repeats', 'repetitive'],
 'attention b8: MentallyStuck': ['stuck'],
 'attention b9: CauseDistress': ['repetitive'],
 'emotion a10: ActHastily': ['hastily', 'careless', 'interrupting'],
 'emotion a11: RapidChanges': ['emotion'],
 'emotion a12: CryingLaughing': ['cry', 'laugh'],
 'emotion a13: OverAnxious': ['anxi', 'panic'],
 'emotion b14: LackOfPleasure': ['pleasure',
  'enjoy',
  'activities',
  'depressi'],
 'emotion b15: NegativeAttitude': ['negative attitude',
  'pessim',
  'hopeless',
  'depressi'],
 'emotion b16: UneasyWithLife': ['uneasy', 'dissatisf', 'depressi'],
 'emotion b17: SadDepressed': ['sad', 'depressi'],
 'autism a18: RepetitiveMovements': ['repetitive',
  'flapping',
  'flicking',
  'rocking',
  'autis'],
 'autism a19: SensoryExp': ['sensory', 'lights', 'autis'],
 'autism b20: Sensitive': ['sensitiv', 'autis'],
 'autism b21: Overwhelmed': ['overwhelm', 'sensitiv', 'stimulat', 'autis'],
 'psychosis a22: Communicates': ['illogical',
  'rambling',
  'nonsensical',
  'irrational',
  'psychotic',
  'psychosis'],
 'psychosis a23: Concerns': ['paranoi', 'psychotic', 'psychosis'],
 'psychosis a24: SeesHearsThings': ['hallucinat'],
 'psychosis b25: TroubleUnderstand': ['feelings'],
 'psychosis b26: Distant': ['distant', 'aloof', 'emotional react'],
 'psychosis b27: Indifferent': ['disinterest',
  'unconcerned',
  'indifferen',
  'activities'],
 'social a28: Angry': ['angry', 'anger', 'aggress'],
 'social a29: Upset': ['upset', 'irritab'],
 'social a30: Intolerant': ['intolerant', 'protective'],
 'social a31: Argumentative': ['disobedien', 'defian', 'argument'],
 'social b32: immature': ['passive', 'immature', 'childlike'],
 'social b33: Unaware': ['social cue', 'inappropriate', 'appropriateness'],
 'social b34: Manner': ['unaware',
  'personal space',
  'social situation',
  'inappropriate'],
 'social b35: Trusting': ['trust', 'trick', 'manipulat', 'gullib']}

In [50]:
finds=[]
to_check=[]
for file in os.listdir(root_folder):

    if not file.endswith('.txt'):
        continue
    
    mrn=int(file.split('.')[0])
    row=merge[merge['MRN']==mrn]
    cols_to_check=row['needs_checking']

    with open(os.path.join(root_folder,file),'r') as f:

        text=f.read().lower()

        in_file=''

        for q, wordlist in keywords.items():
            
            if q not in cols_to_check.iloc[0]:

                continue

            text_out=q+': '
            
            found=False
            for word in wordlist:

                kw_count=text.lower().count(word)

                if kw_count!=0:
                    found=True
                    text_out+=f"{word}:{kw_count},"
            if found:
                in_file+=text_out+'\n'
            
        finds.append([mrn,in_file])

finds_df=pd.DataFrame(finds, columns=['MRN','keywords_counts'])
finds_df

        MRN                                    keywords_counts
0   5709549  attention a3: OntheGo: restless:7,\nattention ...
1   6177575  attention a1: DifficultFocus: focus:5,attentio...
2   7890257  attention a1: DifficultFocus: focus:2,\nemotio...
3   1847722  attention a1: DifficultFocus: focus:13,attenti...
4   4416089  attention a3: OntheGo: restless:47,\nemotion b...
..      ...                                                ...
80  5390756            emotion a11: RapidChanges: emotion:4,\n
81  5741878  attention a2: EasilyDistracted: distract:7,\na...
82  6127951  attention a4: FeelsCompelled: compulsion:1,\na...
83  4552969  attention a1: DifficultFocus: focus:1,detail:1...
84  8014361         emotion b14: LackOfPleasure: pleasure:1,\n

[85 rows x 2 columns]

In [51]:
print(finds_df['keywords_counts'][0])

attention a3: OntheGo: restless:7,
attention b7: Repeats: repeats:8,
autism b21: Overwhelmed: stimulat:5,

In [53]:
output=pd.merge(merge,finds_df,on='MRN')
output=output[[col for col in output.columns if '_sch' not in col]]
output=output[[col for col in output.columns if 'explanation' not in col]]
output.columns=[col.replace('_me','') for col in output.columns]
output

,MRN,attention a1: DifficultFocus,attention a2: EasilyDistracted,attention a3: OntheGo,attention a4: FeelsCompelled,attention a5: FeelsDriven,attention b6: Worries,attention b7: Repeats,attention b8: MentallyStuck,attention b9: CauseDistress,...,social a28: Angry,social a29: Upset,social a30: Intolerant,social a31: Argumentative,social b32: immature,social b33: Unaware,social b34: Manner,social b35: Trusting,needs_checking,keywords_counts
0,6596307,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,"[attention a1: DifficultFocus, attention a2: E...","attention a1: DifficultFocus: focus:23,detail:..."
1,6890459,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,"[attention a1: DifficultFocus, attention a2: E...","attention a1: DifficultFocus: focus:3,detail:3..."
2,6868827,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[attention a1: DifficultFocus, attention a2: E...","attention a1: DifficultFocus: focus:2,attentio..."
3,7298779,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,"[attention a2: EasilyDistracted, attention a3:...",
4,8231339,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[attention a1: DifficultFocus, attention a2: E...","attention a1: DifficultFocus: focus:2,detail:5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,3699762,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,"[attention a1: DifficultFocus, attention a2: E...","attention a1: DifficultFocus: focus:44,attenti..."
81,3815202,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[attention a2: EasilyDistracted, attention a3:...","attention a4: FeelsCompelled: compulsion:7,\na..."
82,1175258,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,[attention b8: MentallyStuck],
83,1847722,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,"[attention a1: DifficultFocus, attention a2: E...","attention a1: DifficultFocus: focus:13,attenti..."
84,8671698,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,"[attention a1: DifficultFocus, attention a2: E...","attention a1: DifficultFocus: focus:7,detail:1..."

In [54]:
output.to_csv("/Users/rm026/Documents/schmahmann/ground_truth_master_list_cnrs_partial.csv" ,index=False)